[dependencies]
  log = "^0.4"
  rand = "^0.8"
  serde_json = "^1.0"
  fastly = "^0.8"
  log-fastly = "^0.8"

[package]
  authors = []
  edition = "2018"
  name = "fastly-fanout"
  publish = false
  version = "0.1.0"

[profile]

  [profile.release]
    debug = 1
